---
- name: Configure Application Servers
  hosts: all
  become: true


  tasks:
    - name: Create default site
      shell: |        
        sudo ee site create {{ tf_ip }}

    # The idea behind the folllowing is to be able to generate an ssh key from the deployed server
    # and then use an API call to store the public key into bitbucket. Unfortunately, bitbucket premium
    # is needed in order to create a Workspace Access Token. Hence, I'll use repository token, while it
    # doesn't allow for API call to store the ssh key, at least it allows to checkout a repository by
    # using the repository token: https://support.atlassian.com/bitbucket-cloud/docs/repository-access-tokens/
    # ref: https://support.atlassian.com/bitbucket-cloud/docs/access-tokens/
    # ref: https://stackoverflow.com/questions/66303064/ansible-add-public-key-to-bitbucket-and-checkout-the-repo    
    #
    # - name: Create access key
    #   community.general.bitbucket_access_key: 
    #     repository: '{{ tf_frontend_repo }}'
    #     client_id: xxxxxxxxx # Key generated by Bitbucket
    #     client_secret: xxxxxxxxxxxxxx # Secret generated by Bitbucket
    #     username: 
    #     key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    #     label: 'device'
    #     state: present

    - name: Create soft link to easy-engine sites directory
      shell: |
        cd
        ln -s /opt/easyengine/sites/ /home/{{ tf_ansible_username }}/sites

    - name: Remove default htdocs site directory
      shell: |
        cd
        rm -rf /home/{{ tf_ansible_username }}/sites/{{ tf_ip }}/app/htdocs

    - name: Download the repository [bitbucket]
      git:
        #key_file: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa') }}"
        repo: 'https://x-token-auth:{{ tf_repo_access_token }}@bitbucket.org/{{ tf_frontend_repo }}.git'
        dest: /home/{{ tf_ansible_username }}/sites/{{ tf_ip }}/app/htdocs/
        #depth: '1'
        force: yes
        #accept_hostkey: yes        

    - name: Reload default site
      shell: |
        ee site reload {{ tf_ip }}

    - name: Add email in easy-engine config for wildcard-SSL validation
      lineinfile:
        path: /opt/easyengine/config/config.yml
        state: present        
        line: 'le-mail: {{ tf_mail }}'

    # - name: Create domain site
    #   shell: |
    #     sudo ee site create {{ tf_domain }} --ssl=le --wildcard<<<$'{{ tf_mail }}\n' > /home/{{ tf_ansible_username }}/output.txt
    #   args:
    #     executable: /bin/bash

    - name: Create domain site
      shell: |
        sudo ee site create {{ tf_domain }} --ssl=le --wildcard > /home/{{ tf_ansible_username }}/output.txt
      # args:
      #   executable: /bin/bash   $ default is dash, not bash. dash doesn't recognize hereString for input ( <<<$'foobar' )

    - name: Remove default htdocs site directory
      shell: |
        cd
        rm -rf /home/{{ tf_ansible_username }}/sites/{{ tf_domain }}/app/htdocs

    - name: Download the repository [bitbucket]
      git:
        #key_file: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa') }}"
        repo: 'https://x-token-auth:{{ tf_repo_access_token }}@bitbucket.org/{{ tf_frontend_repo }}.git'
        dest: /home/{{ tf_ansible_username }}/sites/{{ tf_domain }}/app/htdocs/
        #depth: '1'
        force: yes
        #accept_hostkey: yes        

    - name: Reload default site
      shell: |
        ee site reload {{ tf_domain }}


    - name: Copy script
      copy:
        src: ./get_validationTXT.sh
        dest: /home/{{ tf_ansible_username | quote }}/get_validationTXT.sh
        owner: ansible
        mode: '0744'