---
- name: Configure Application Servers
  hosts: all
  become: true

  tasks:
    - name: Create default site
      shell: |        
        sudo ee site create {{ tf_ip | quote }}

    - name: Create soft link to easy-engine sites directory
      shell: |        
        ln -s /opt/easyengine/sites/ /home/{{ tf_ansible_username | quote }}/sites

    - name: Remove default htdocs site directory
      shell: |        
        rm -rf /home/{{ tf_ansible_username }}/sites/{{ tf_ip }}/app/htdocs

    - name: Download the repository [bitbucket]
      git:        
        repo: 'https://x-token-auth:{{ tf_repo_access_token }}@bitbucket.org/{{ tf_frontend_repo }}.git'
        dest: /home/{{ tf_ansible_username }}/sites/{{ tf_ip }}/app/htdocs/
        #depth: '1'
        force: yes
        #accept_hostkey: yes        

    - name: Reload default site
      shell: |
        ee site reload {{ tf_ip | quote }}

    - name: Set email in easy-engine config for wildcard-SSL validation
      shell: |
        ee config set le-mail {{ tf_mail | quote }}

    - name: Set cloudflare global api key in easy-engine config for wildcard-SSL validation
      shell: |        
        ee config set cloudflare-api-key {{ tf_cf_global_api | quote }}

    - name: Create domain site using let's encrypt's wildcard certificate
      shell: |
        sudo ee site create {{ tf_domain | quote  }} --ssl=le --wildcard

    - name: Verify wildcard SSL cert with DNS method using cloudflare global api key
      shell: |        
        ee site ssl-verify {{ tf_domain | quote }}

    - name: Remove default htdocs site directory
      shell: |        
        rm -rf /home/{{ tf_ansible_username }}/sites/{{ tf_domain }}/app/htdocs

    - name: Download the repository [bitbucket]
      git:
        repo: 'https://x-token-auth:{{ tf_repo_access_token }}@bitbucket.org/{{ tf_frontend_repo }}.git'
        dest: /home/{{ tf_ansible_username }}/sites/{{ tf_domain }}/app/htdocs/
        #depth: '1'
        force: yes
        #accept_hostkey: yes        

    - name: Reload default site
      shell: |
        ee site reload {{ tf_domain }}